import { type PropsWithChildren } from 'react';
import type { ChannelId, Role } from '../domain/types';
import { useCockpitContext, type PeriodPreset } from '../hooks/useCockpitData';

const channelNames: Record<ChannelId, string> = { tmall: '淘宝/天猫', jd: '京东', douyin: '抖音' };
const roleNames: Record<Role, string> = { operator: '运营专员', manager: '运营主管', executive: '管理层' };
const periods: Array<{ id: PeriodPreset; label: string }> = [{ id: 'yesterday', label: '昨日' }, { id: 'last_7_days', label: '近 7 天' }, { id: 'month', label: '本月' }, { id: 'custom', label: '自定义' }];

export function AppShell({ children }: PropsWithChildren) {
  const { filters, role, setPeriod, toggleChannel, setRole, setCustomRange } = useCockpitContext();
  return <div className="app-shell"><aside className="sidebar" aria-label="主导航"><div className="brand-mark"><span>智</span><div><b>智营</b><small>RPA DATA COCKPIT</small></div></div><nav className="nav-list"><a className="nav-item active" href="#overview">▦　经营总览</a><a className="nav-item" href="#daily-report">◫　每日经营日报</a><a className="nav-item" href="#anomalies">◇　异常中心 <em>5</em></a><a className="nav-item" href="#sku-analysis">▤　商品分析</a><a className="nav-item" href="#automation">◌　自动化任务</a><a className="nav-item" href="#integrations">⌘　数据接入与规则</a></nav><div className="sidebar-footer"><span className="live-dot" />所有数据均为模拟、脱敏数据</div></aside><section className="workspace"><header className="topbar"><div><p className="eyebrow">运营自动化 · 演示环境</p><h1>智营 RPA 数据驾驶舱</h1></div><div className="top-actions"><span className="refresh-status"><i />模拟数据 · 每日 08:30 刷新</span><button className="export-button">导出当前报表 <span>↓</span></button></div></header><section className="filterbar" aria-label="全局筛选"><div className="filter-group"><span className="filter-label">时间范围</span><div className="segmented-control">{periods.map(({ id, label }) => <button key={id} className={filters.period === id ? 'selected' : ''} onClick={() => setPeriod(id)}>{label}</button>)}</div></div>{filters.period === 'custom' && <div className="custom-dates"><input aria-label="开始日期" type="date" defaultValue="2026-07-17" onChange={(e) => setCustomRange({ from: e.target.value, to: filters.customRange?.to ?? '2026-07-23' })} /><span>至</span><input aria-label="结束日期" type="date" defaultValue="2026-07-23" onChange={(e) => setCustomRange({ from: filters.customRange?.from ?? '2026-07-17', to: e.target.value })} /></div>}<div className="filter-divider" /><div className="filter-group"><span className="filter-label">渠道</span><div className="channel-pills">{(Object.keys(channelNames) as ChannelId[]).map((channel) => <button key={channel} aria-pressed={filters.channels.includes(channel)} className={filters.channels.includes(channel) ? 'selected' : ''} onClick={() => toggleChannel(channel)}>{channelNames[channel]}</button>)}</div></div><div className="filter-spacer" /><div className="role-switcher" aria-label="演示角色切换">{(Object.keys(roleNames) as Role[]).map((item) => <button key={item} className={role === item ? 'selected' : ''} onClick={() => setRole(item)}>{roleNames[item]}</button>)}</div></section><main className="content-area">{children}</main></section></div>;
}
